-- 감탄위크 Vercel + Supabase 운영구조 업그레이드
-- 1회 실행: 생년월일 로그인, 관리자 역할 분리, 오프라인 300부/6개 지점 관리

begin;

-- 1) 참여자 로그인: 생년월일 6자리는 원문을 저장하지 않고 해시/솔트만 저장합니다.
alter table public.participants add column if not exists birth_hash text;
alter table public.participants add column if not exists birth_salt text;

-- 2) 운영 설정: 오프라인 일기장 총수량
insert into public.app_settings (setting_key, setting_value)
values ('OFFLINE_DIARY_TOTAL', '300')
on conflict (setting_key) do update
set setting_value = excluded.setting_value,
    updated_at = now();

-- 3) 관리자 계정
create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  display_name text not null,
  password_hash text not null,
  password_salt text not null,
  role text not null check (role in ('super_admin','org_admin')),
  organization_id text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists admin_users_org_idx on public.admin_users (organization_id);

-- 4) 오프라인 일기장 배포지점 6곳
create table if not exists public.offline_sites (
  id uuid primary key default gen_random_uuid(),
  organization_id text not null,
  organization_name text not null,
  site_name text not null unique,
  address text,
  opening_hours text,
  allocated_quantity integer not null default 0 check (allocated_quantity >= 0),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 기관 테이블에 같은 이름이 있으면 그 id를 사용하고, 없으면 오프라인 전용 식별자를 사용합니다.
insert into public.offline_sites
(organization_id, organization_name, site_name, address, opening_hours, sort_order)
values
(
  coalesce((select id::text from public.organizations where organization_name ilike '%지구상점%' order by sort_order nulls last limit 1), 'offline:jigu'),
  '지구상점', '지구상점', '황교길 58, 1층', '월~금 09:00~17:00', 1
),
(
  coalesce((select id::text from public.organizations where organization_name ilike '%원주신협%' order by sort_order nulls last limit 1), 'offline:wonju-credit-union'),
  '원주신협', '원주신협 본점', '중앙로 118', '월~금 09:00~16:00', 2
),
(
  coalesce((select id::text from public.organizations where organization_name ilike '%원주신협%' order by sort_order nulls last limit 1), 'offline:wonju-credit-union'),
  '원주신협', '원주신협 단계지점', '천사로 61', '월~금 09:00~16:00', 3
),
(
  coalesce((select id::text from public.organizations where organization_name ilike '%원주신협%' order by sort_order nulls last limit 1), 'offline:wonju-credit-union'),
  '원주신협', '원주신협 남부지점', '서원대로 410', '월~금 09:00~16:00', 4
),
(
  coalesce((select id::text from public.organizations where organization_name ilike '%원주신협%' order by sort_order nulls last limit 1), 'offline:wonju-credit-union'),
  '원주신협', '원주신협 섬강지점', '신지정로 322', '월~금 09:00~16:00 · 12:00~13:00 미운영', 5
),
(
  coalesce((select id::text from public.organizations where organization_name ilike '%청소년수련관%' order by sort_order nulls last limit 1), 'offline:youth-center'),
  '원주시청소년수련관', '원주시청소년수련관', '서원대로 234, 이음관 1층', '화~토 10:00~20:00', 6
)
on conflict (site_name) do update set
  organization_id = excluded.organization_id,
  organization_name = excluded.organization_name,
  address = excluded.address,
  opening_hours = excluded.opening_hours,
  sort_order = excluded.sort_order,
  updated_at = now();

-- 5) 담당자가 수시로 입력하는 배포/제출 기록
create table if not exists public.offline_distribution_entries (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null references public.offline_sites(id) on delete restrict,
  organization_id text not null,
  entry_date date not null default current_date,
  distributed_qty integer not null default 0 check (distributed_qty >= 0),
  submitted_qty integer not null default 0 check (submitted_qty >= 0),
  note text,
  entered_by_admin_id text not null,
  created_at timestamptz not null default now()
);
create index if not exists offline_entries_site_date_idx on public.offline_distribution_entries (site_id, entry_date desc);
create index if not exists offline_entries_org_idx on public.offline_distribution_entries (organization_id);

-- 6) 관리자 열람/변경 기록
create table if not exists public.admin_access_logs (
  id bigint generated by default as identity primary key,
  admin_user_id text not null,
  admin_role text,
  organization_id text,
  action text not null,
  target_type text,
  target_id text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_access_logs_created_idx on public.admin_access_logs (created_at desc);
create index if not exists admin_access_logs_admin_idx on public.admin_access_logs (admin_user_id);

-- 브라우저가 DB를 직접 읽지 못하게 유지합니다. Vercel 서버 API만 Secret Key로 접근합니다.
alter table public.admin_users enable row level security;
alter table public.offline_sites enable row level security;
alter table public.offline_distribution_entries enable row level security;
alter table public.admin_access_logs enable row level security;

commit;

-- 확인용 결과
select setting_key, setting_value from public.app_settings where setting_key in ('ONLINE_APPLICATION_LIMIT','OFFLINE_DIARY_TOTAL') order by setting_key;
select organization_name, site_name, address, allocated_quantity from public.offline_sites where is_active = true order by sort_order;
